export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const INCREMENT_CART_COUNT = 'INCREMENT_CART_COUNT';
export const DECREMENT_CART_COUNT = 'DECREMENT_CART_COUNT';
export const INCREMENT_PRODUCT_QTY = 'INCREMENT_PRODUCT_QTY';
export const DECREMENT_PRODUCT_QTY = 'DECREMENT_PRODUCT_QTY';
